name: repeat_exam
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.3+4
environment:
  sdk: ^3.10.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  flutter_colorpicker: ^1.1.0
  flex_seed_scheme: 4.0.1
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  flutter_launcher_icons: 0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/icons/icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/json/exams/
    - assets/icons/
    - shorebird.yaml

